export const HANDLE_PUBLIC_FILTER = 'HANDLE_PUBLIC_FILTER';
export const HANDLE_ADMIN_FILTER = 'HANDLE_ADMIN_FILTER';
export const HANDLE_PUBLIC_PRICE = 'HANDLE_PUBLIC_PRICE'
export const HANDLE_ADMIN_PRICE = 'HANDLE_ADMIN_PRICE'